### PR TITLE
Apply changes from trac ticket 67.

### PR DESCRIPTION
**Pull request by rhattersley**
See http://cf-trac.llnl.gov/trac/ticket/67

### CODE REVIEW

**Comment by marqh** [comment]
consistent with hash67

**Comment by rhattersley** [comment]
@marqh - you might want to hold fire for a bit. I think my PRs need to include updates to the "Revision history".

**Comment by marqh** [comment]
apologies: would you like me to revert, or is a follow up PR useful.

I confess I think that this a small editorial change, not requiring a 'Revision History' entry, but i am very easily swayed from that point of view

**Comment by rhattersley** [comment]
Other similarly small defects have their own entry in the revision history, so since we're sticking with that way of recording changes I think it's needed here too.

I don't a revert is needed - I'll handle it in a follow-up.

**Pull request merged**
