### PR TITLE
Correct figures & add static assets to HTML check build

### PR DESCRIPTION
**Pull request by erget**
See issue #295 for discussion of these changes.

# Release checklist
- [x] Authors updated in `cf-conventions.adoc`?
- [x] Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
- [x] `history.adoc` up to date?
- [x] Conformance document up-to-date?

# For maintainers
After the merge remember to delete the source branch.
Tags are set at the conclusion of the annual meeting; until then `master` always is a draft for the next version.

### CODE REVIEW

**Comment by erget** [comment]
Pending contribution from @neumannd for finalisation.

**Comment by neumannd** [comment]
@erget I updated the figures but have to find out how to add things to your PR. I'll do it today afternoon (and update the text in the figure captions).

**Comment by erget** [comment]
@neumannd OK don't worry, this isn't urgent, I just like to make sure the next steps are clear before I switch tasks :) If you send me a PR to this branch from your branch I can merge it and it'll get included for pulling into the main repo. Let me know if you need a hand, I'll be around this afternoon.

**Comment by neumannd** [comment]
@erget I send you an email with the modified files. Hope, that I guessed your email adress correctly.

**Pull request merged**
