### PR TITLE
update bot token

### PR DESCRIPTION
**Pull request by marqh**
See issue #177 or discussion of these changes.

### CODE REVIEW

**Comment by marqh** [comment]
may be able to replace
#182 

however, this can only really be tested by merging it, as it will only run and use the token on master

if people are uncomfortable with this, I can make a branch on the main repository to prove the implementation, and make it push to another branch, but this is more work

**Comment by marqh** [comment]
to keep the implementation clean, it would be good to remove the CI Environment variable changes made to facilitate
#182 as these are re-using environment variables, which could then conflict

I'm happy to do this before merge, if someone aims to merge this

consideration of this approach compared to #182 is useful, I feel

I hope this is helping

**Comment by dblodgett-usgs** [comment]
I'll take care of it and go ahead and merge here. It's not going to get any more broken.

**Comment by marqh** [comment]
```
 	cf-conventions.html 	Auto-generated from a884f3e 	14 seconds ago
	cf-conventions.pdf 	Auto-generated from a884f3e 	14 seconds ago
```

I believe we are cooking
:)

**Comment by marqh** [comment]
thank you @dblodgett-usgs

**Pull request merged**
