### PR TITLE
#85

### PR DESCRIPTION
**Pull request by reshel3**
#85 Added sentence to bottom of first para in Section 9.1 "Features and feature types".  Added Links column in Section 9.1 Replaced first para in Section 9.6. "Missing Data". Added verbiage to
Section 2.5.1, "Missing data...".  Added sentence to Appendix A "Description" "missing_value" and "Fill_Value".

### CODE REVIEW

**Comment by davidhassell** [comment]
Text looks good - thanks. The table in section 9.1 seems to have largely gone (https://github.com/reshel3/cf-conventions/blob/f920496dbd92a3177020aa6ab2954e1818e66e5b/ch09.adoc) - or am I looking at in the wrong way?

**Comment by JonathanGregory** [comment]
I see the same as David when viewing the whole modified file for chapter 9. The table contents have disappeared. Jonathan

**Comment by JonathanGregory** [comment]
It looks like the links in the table in ch 9 aren't actually links yet. They should be links to the corresponding sections of Appendix H. Cheers, Jonathan

**Comment by painter1** [comment]
The links are in another branch, reshel-85.   They will make it in here when the merger process is finished.

**Comment by painter1** [comment]
We're closing this pull request, unmerged.  All the changes in this one are incorporated in another pull request which I will issue shortly.

**Pull request closed without merging**
