### PR TITLE
Incorporating the CF data model into the conventions

### PR DESCRIPTION
**Pull request by davidhassell**
See issue #159 for discussion of these changes.

### CODE REVIEW

**Comment by zklaus** [comment]
There seem to be some technical problems at this point: `appi.adoc` is not included in `cf-conventions.adoc`, probably something like
```
:numbered!:
include::appi.adoc[]

```
should be added to the end of the list of appendices.

When I do that locally, the document doesn't compile to pdf anymore.
I'll see if I can submit a PR/fix for that.

**Comment by zklaus** [comment]
Also, the png figures don't scale very well. Any chance of svg, pdf, or eps versions?

**Comment by davidhassell** [comment]
Thanks - I have updated `cf-conventions.adoc` to include `appi.adoc`. And thank you for investigating why it doesn't build.

I should `.eps` have versions of the figures - I'll have a look

**Comment by zklaus** [comment]
That would be great. It looks like standard uml class diagrams. Maybe you even have the source figures still?

**Comment by davidhassell** [comment]
Hi @zklaus I have added PDF versions of the images in the `images`. I haven't changed the "png" references in the text because when I did the GitHub rendering at https://github.com/davidhassell/cf-conventions/blob/CF_data_model/appi.adoc ignored them. Can you help? 

I would like to merge this PR soon so that the text can be further worked on. It would be really nice to get the figures right first, but if there are difficulties with this, going ahead and merging with the PNG images and working on this aspect later would be fine by me.

Many thanks,
David

**Comment by JonathanGregory** [comment]
Implements https://github.com/cf-convention/cf-conventions/issues/159

**Pull request merged**
