### PR TITLE
Use SVG images for Chapter 7 figures 1 and 2

### PR DESCRIPTION
**Pull request by DocOtak**
This was inspired by the awesome work in #522 

I've converted the two remaining png figured into svgs from the PDFs using svg2pdf from the cairo library. This saves about 300kb from the html build and about 100kb in the pdf builds. All while higher quality.

This is actually my first PR to the actual conventions repository, my change is just technical and I feel it does not need the addition of my name to the authors list.

See issue #XXX for discussion of these changes.

# Release checklist
- [ ] Authors updated in `cf-conventions.adoc`? Add in two places: on line 3 and under `.Additional Authors` in `About the authors`.
- [ ] Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
- [ ] `history.adoc` up to date?
- [ ] Conformance document up to date?

# For maintainers
After the merge remember to delete the source branch.
Tags are set at the conclusion of the annual meeting; until then, `main` always is a draft for the next version.

### CODE REVIEW

**Comment by neumannd** [comment]
@DocOtak I could re-created the figures directly as svg files (I created these figures in the first place).

**Comment by DocOtak** [comment]
@neumannd How did you create the figures in the first place? It might it be worth adding the "source" to this repository. The pdf2svg tool does a pretty good job when the input is already a vector of some sort and these PDFs were.

**Comment by neumannd** [comment]
@DocOtak 

> How did you create the figures in the first place?

I created them with a small R script. 

> It might it be worth adding the "source" to this repository.

Sure. Sounds reasonable. To which location should I copy/push the code? Or just as a comment into the document?

> The pdf2svg tool does a pretty good job when the input is already a vector of some sort and these PDFs were.

OK. Then, I won't re-create them as SVG.

**Comment by DocOtak** [comment]
We should open an issue/discussion to ask how and where the sources should be added. Did you make any other figures than these two?

If it is easy to do, I'd like to know if the direct SVG output is smaller/more efficient than this conversion. The SVG output from this is about 60kb each, where the PDFs are 5kb each.

**Comment by neumannd** [comment]
> We should open an issue/discussion to ask how and where the sources should be added. Did you make any other figures than these two?

Only these two -- as far as I remember.
 
> If it is easy to do, I'd like to know if the direct SVG output is smaller/more efficient than this conversion. The SVG output from this is about 60kb each, where the PDFs are 5kb each.

The SVGs are slightly large than the PDFs but not 10x as large:

```
$ ls -la
...   5554 21. Okt 12:21 order_horizontal_bounds__1D_coord_variables.svg
... 110084 21. Okt 12:21 order_horizontal_bounds__1D_coord_variables.png
...   4751 21. Okt 12:21 order_horizontal_bounds__1D_coord_variables.pdf
...   5107 21. Okt 12:23 order_horizontal_bounds__2D_coord_variables.pdf
...   8944 21. Okt 12:23 order_horizontal_bounds__2D_coord_variables.svg
... 228137 21. Okt 12:23 order_horizontal_bounds__2D_coord_variables.png
```

I attached them.

order_horizontal_bounds__1D_coord_variables
order_horizontal_bounds__2D_coord_variables

**Comment by cofinoa** [comment]
@neumannd, while we decide what to do with the original scripts, could you please add both R scripts to the images directory and name them as follows:
```
order_horizontal_bounds__1D_coord_variables.R
order_horizontal_bounds__2D_coord_variables.R
```
Additionally, could you include a comment or header in each script indicating the R version and any dependencies, if applicable?

**Comment by neumannd** [comment]
@DocOtak OK. I'll do so tomorrow or later today. As an extra PR refering to this on?

**Comment by neumannd** [comment]
@DocOtak I created a pull request to your branch DocOtak:svg_figures. Then, we have everything in this on PR to the cf-conventions. I added version requirements to the top of the R code. I am not sure whether the way I did conforms to any standard or not. Maybe, it works with lower version as well.

**Comment by DocOtak** [comment]
@neumannd merged, it should update this PR automatically

**Comment by neumannd** [comment]
@DocOtak Worked. But, I forgot to update paths in the code => new PR to your branch. Sorry for that.

**Review by cofinoa — APPROVED** [review]
I have tested locally and the build and docs are good!!

**Pull request merged**
