### PR TITLE
Check that PRs do not break Asciidoctor build

### PR DESCRIPTION
**Pull request by lesserwhirls**
This PR enables a github action to check that PRs do not break the asciidoc build. If the build is successful, the pdf and html files are uploaded as artifacts to the action, which allow for easier previews of the generated files.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
As an example of what this will look like, see [here](https://github.com/lesserwhirls/cf-conventions/actions/runs/58486955).

**Comment by marqh** [comment]
I agree this is a useful and sensible step

thank you for the input @lesserwhirls

**Comment by lesserwhirls** [comment]
Thanks @marqh! Happy to help where I can :-)

**Comment by zklaus** [comment]
This is great!
Would it be possible to upload the pdf and html individually, not in an archive so as to facilitate easy inspection?
Maybe it would also be a good idea to upload a log (perhaps just the console output)?
Like this, we might catch some warnings more easily that don't prevent a successful creation, but would be nice to know anyways.

**Comment by lesserwhirls** [comment]
> This is great!
> Would it be possible to upload the pdf and html individually, not in an archive so as to facilitate easy inspection?

That would be great! Currently, the `actions/upload-artifact` github action does not support it, but it's on their list of improvements (more info [here](https://github.com/actions/upload-artifact/issues/3#issuecomment-598820814)). 

> Maybe it would also be a good idea to upload a log (perhaps just the console output)?
> Like this, we might catch some warnings more easily that don't prevent a successful creation, but would be nice to know anyways.

I've updated this PR to enable the asciidoctor build to use the `--verbose` flag, which seems to show warnings. An example of what the output looks like now can be found [here](https://github.com/lesserwhirls/cf-conventions/runs/528953848#step:5:5).

**Comment by ethanrd** [comment]
Two positive reviews and it looks good to me. I'm going to merge.

I will look at how to require reviews for this type of PR, probably by members of the [info-mgmt](https://github.com/orgs/cf-convention/teams/info-mgmt/members) team - @cf-convention/info-mgmt

**Pull request merged**
