### PR TITLE
87

### PR DESCRIPTION
**Pull request by reshel3**
87 - Changed in Appendix A,  "Comment" attribute from G, D to G, C, D

### CODE REVIEW

**Comment by painter1** [comment]
What's the ticket number for this change?

**Comment by painter1** [comment]
I'm sorry, I see that the ticket number is the title of this pull request.

Anyway, the change is exactly correct.  All we need is an entry in the Revision History.

**Comment by davidhassell** [comment]
Who does have write access? I don't think I do! I presume that Richard Hattersley does...anyone else?

**Comment by painter1** [comment]
Write access to what?  Probably you want to be on the "Devel Team".  It has 21 members.  I'll send you an invitation.  Probably that will do what you need.

**Comment by painter1** [comment]
David, you have already been invited to the devel team.  I don't see a way to re-send the invitation, so if you can't find it, please let me know.  Then I'll cancel the invitation and create a new one.

**Comment by painter1** [comment]
updated revision history and merged from the command line

**Pull request merged**
