### PR TITLE
Add explanation of status_flag, quality_flag, other QC flag standard names to Chapter 3.4

### PR DESCRIPTION
**Pull request by mwengren**
See issue #216 for discussion of these changes, specifically in the [comment on Dec 10](https://github.com/cf-convention/cf-conventions/issues/216#issuecomment-564107540) suggesting adding to the CF documentation usage examples for `status_flag`, `quality_flag`, and related QC flag standard names proposed in #216.

**This PR includes the following:**

- adds to Chapter 3.4 new text describing usage of ancillary variables as status/quality flags, and a new example, currently numbered '3.2.1' pending agreement on where this section belongs in the docs. (I used '3.2.1' because I didn't want to renumber all the examples until there was agreement on whether this text and example is in the proper location with respect to other material in Chaps 3.4 and 3.5)
- resolves a mis-ordering issue in the accompanying text for Example 3.4 in the master branch of draft 1.8 docs (text for Example 3.4 and Example 3.5 appear to be reversed). 
- corrects a dead link in toc-extra.adoc (the current master branch includes duplicate links in the 'List of Examples' section to Example 3.5 - i.e. both Example 3.4 and 3.5 links point to 3.5).  This PR fixes the dead link to Example 3.4.
- adds `status_flag` attributes to Example 3.5 as suggested in #216 and earlier discussions in the CF mailing list surrounding the addition of `quality_flag`.  See [this thread](http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2019/020995.html) in the CF list archives for related discussion.

I will revise the PR to change Example 3.2.1 to 3.3 (or whichever appropriate number)  when there's agreement on whether and where this addition belongs, bumping the other Chapter 3 example numbers accordingly.

cc @davidhassell: Because this PR resolves some outstanding issues in the 1.8 CF docs, may I suggest it be considered for inclusion before CF 1.8 is released next month?  I know it's late to the game, but I think it will benefit the new release overall.  The release notice you sent out a few days ago prompted me to polish off this PR and submit in case.  

Happy to revise content of descriptions or examples if necessary, some rewording may be needed.  I see several phrases I'd like to change in putting this PR together.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
Just noting that this has been open for far too long. @davidhassell and @roy-lowry are called out as reviewers. What's the status?

**Comment by roy-lowry** [comment]
Fell off my radar I'm afraid - it's been rather a distracting year with illness and getting caught up in Portugal during lockdown.....

I now have time so will pick it up.

**Comment by roy-lowry** [comment]
Right I've read through the proposed modified text (an embarrassingly small amount) and am happy for it to be merged into the Conventions. Again apologies for being so tardy and thanks to @dblodgett-usgs for the reminder!

I have never reviewed anything on GitHub before. Is this comment sufficient to sign off the review or is there something else I need to do?

**Comment by cameronsmith1** [comment]
> I have never reviewed anything on GitHub before. Is this comment sufficient to sign off the review or is there something else I need to do?

Hi, @roy-lowry .  Since you are an assigned reviewer, there should be a review or approve button somewhere on this page that you can click.  I am not sure whether CF is requiring this, but it should be easy to do, and it makes it easier to check all the reviewers approve.

**Comment by roy-lowry** [comment]
@cameronsmith1 Many thanks. Button found and job done.

**Comment by mwengren** [comment]
@roy-lowry Thanks for the review.  

@dblodgett-usgs I believe I need to rebase this branch against the master branch as it contains some outdated fixes to the docs that were already merged in #240.  Had planned to address this but hadn't yet.

Please hold off on merging until I can tackle this, hopefully tomorrow.  I see GitHub has found the conflicts, but I have not used the GitHub-based Resolve Conflicts feature before, so holding off on that approach for the moment..  

Will ping you again once resolved.

**Comment by mwengren** [comment]
@roy-lowry @dblodgett-usgs 

Apologies, but I've managed to totally clobber the branch associated with this PR in attempting to bring it in line with the master branch, squash commits, etc.  Clearly went above my GitHub PR updating abilities.  

I created a new branch that is current with master and has only minor changes to the text of this original PR - mostly to bring it in line with discussions that happened in #216 subsequent to when I originally filed this.  New PR: #264.

Can you please review the PR connected to the new branch instead?  Hopefully these new changes will be agreeable.  The new PR also re-orders the subsequent example numbers in Chapter 3.4 since @roy-lowry originally approved this version with the new example as ordered.

I am going to close this PR to simplify things.

**Pull request closed without merging**
