### PR TITLE
All The Things ~Matthew

### PR DESCRIPTION
**Pull request by reshel3**
@mattben is submitting this on behalf of @reshel3
This PR includes
* #80 
* #70 
* #104
* #118
* #86 
* update_revision_history
* #76 
* #138
* #109
* #102

See http://cf-trac.llnl.gov/trac/ticket/XXX

 - [ ] Added link from trac ticket to this PR?

 > Applied via ​https://github.com/cf-convention/cf-conventions/pull/XXX

 - [ ] Updated "Revision History"? (Use the date you applied the changes.)

### CODE REVIEW

**Comment by painter1** [comment]
Branch 118 (at least) has already been merged in.  Other branches haven't been merged yet.  The contents of 80 were substantially revised and incorporated into another branch which has its own pull request.  I'll look at this tomorrow, but my first reaction is to think that these branches should be reviewed and merged one at a time.

**Comment by mattben** [comment]
@painter1 at this point it be easier for us all to just merge this, and then make corrections (new issues). Having to re do them would take longer and be a waste of man power.

**Comment by painter1** [comment]
They don't have to be redone.  What I've been doing is checking out into a new branch, updating the Revision History (which generally needs a new date), then issuing a pull request.  I have never had to re-do anything Tanya had done.  But finding all the errors from a massive automated merge sounds like a nightmare.

**Comment by davidhassell** [comment]
As a reviewer, I find it much easier to look self-contained changes from one ticket ata time.

Thanks, David

**Comment by mattben** [comment]
If that makes your life easier, cool beans. You'll just have to pull each of her branches, pull upstream/master correct the merge conflicts  and then create a new PR (10 times). Not impossible or hard just very time assuming. Good luck!

@painter1 @reshel3 @davidhassell

**Comment by painter1** [comment]
All changes in this pull request have been incorporated in other branches which have been merged into the master branch, and some time ago.  So I'll close this pull request.

**Pull request closed without merging**
