### PR TITLE
Fix #306

### LINKED ISSUE #306: Note in CONTRIBUTING for Conventions: Moderator should keep summary up to date and post in comments when updates so that people get pinged
This was agreed at the 2020 Community Meeting and has since been enshrined in practice but not in text. I will propose a text that makes this part of the tasks for which a moderator takes responsibility.

### PR DESCRIPTION
**Pull request by erget**
See issue #306 for discussion of these changes.

### CODE REVIEW

**Review by sadielbartholomew — APPROVED** [review]
Not sure if you were waiting on a review for this, but in case you are, I've had a look and this resolves the issue at hand, and the formatting of it renders as it should, so it's all good to merge as far as I am concerned.

**Comment by erget** [comment]
@sadielbartholomew thanks, wasn't my expectation for you personally but it's a welcome review!

**Comment by sadielbartholomew** [comment]
> wasn't my expectation for you personally

Of course, sorry, I just meant for a review in general by someone admin-aligned. It came up in my notifications and I read it so thought why not review!

**Comment by erget** [comment]
@sadielbartholomew absolutely no problem - I was happy you reviewed, I just didn't want you to think I thought you had an obligation to do so :)

**Pull request merged**
