### PR TITLE
New Table D.1 format

### PR DESCRIPTION
**Pull request by painter1**
I replaced Table D.1 with one formatted as requested by Karl Taylor.

### CODE REVIEW

**Comment by painter1** [comment]
The main problem I had was that the title is long, and AsciiDoc cannot wrap a block title.  My solution was to use half the title for one, blank, table and the other half of the title for the real table - rather kludgy.

**Comment by painter1** [comment]
Actually GitHub's AsciiDoc engine seems to be able to wrap a block title.  It's asciidoctor that can't.

**Comment by taylor13** [comment]
Hi Jeff,

This looks good to me.  I think the title would be clearer if it began:  "Consistent sets of values for the standard_names of formula terms and the computed_standard_name ... "  If you agree, why don't you go ahead and change it and call it done.
thanks,
Karl

**Comment by painter1** [comment]
I've changed the title.  As I mentioned elsewhere, my workaround to Asciidoctor limitations leads to a harmless but ugly horizontal line in the title.  But there's no better alternative which I can find.  So I also think we're done now.

**Comment by painter1** [comment]
I solved that title problem.  I did it working directly in the master branch because I had to test it with asciidoctor-pdf as well as asciidoctor, and a firewall problem has kept me from installing asciidoctor-pdf.

It turns out that asciidoctor and asciidoctor-pdf _will_ wrap the title of a figure.  So I put the entire title on a figure, right before the table.  The image displayed is 1 pixel and transparent, hence invisible.  So it looks like the table's title.

**Pull request merged**
