### PR TITLE
Updates concerning the Polar Stereographic Grid Mapping

### PR DESCRIPTION
**Pull request by sadielbartholomew**
See issue #445 for discussion of these changes.

# Release checklist
- [x] Authors updated in `cf-conventions.adoc`?
- [x] Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
- [x] `history.adoc` up to date?
- [x] Conformance document up-to-date?

# For maintainers
After the merge remember to delete the source branch.
Tags are set at the conclusion of the annual meeting; until then, `main` always is a draft for the next version.

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
I will address the remaining three checklist points shortly, in a few new commits. For now, FYI the commits so far are the actual changes which implement, with corresponding numbering, the points from my accepted proposal summary https://github.com/cf-convention/cf-conventions/issues/445#issuecomment-1723181737.

**Comment by sadielbartholomew** [comment]
Quick question: does `cf-conventions.adoc`need amending given this Issue? I am not sure if my proposal in #445 and this PR to implement it merit my name being added to the 'Additional Authors' list for the overall canonical document. I suspect not, but can someone confirm what if anything needs to be done in this case?

**Comment by sadielbartholomew** [comment]
(My question of the previous comment has been answered by Jonathan over on the linked Issue. And a merge conflict has resolved itself with my updates.)

Since all updates have been made as discussed on the Issue and I've completed all (applicable) release checklist items, I believe this is now ready for review   :slightly_smiling_face:

**Comment by larsbarring** [comment]
I just saw that your PR is marked by github as "This branch has no conflicts with the base branch". Nevertheless the two entries in Table F1 `sweep_angle_axis` and `fixed_angle_axis` are shown with the backticks visible. This is becasue the right backticks are preceded by a space. This is something that I (again) saw yesterday in the published document. This time I decided to fix it immediately and made a PR that just removed the two rogue spaces. And then I ventured to immediately merge it myself, because it was such trivial change, and saw that it now looks all right in the published version. I guess that you did not did fetch and rebased on the new main (since yesterday evening), which is very reasonable. But what puzzles me is that this conflict is not identified by github.

**Comment by sadielbartholomew** [comment]
That's interesting, good spot @larsbarring. `git`almost always handles things like this well under-the-hood, and reports accurately, so I am surprised if it is not behaving right. GitHub itself is more flaky, but the GitHub Status site is not telling of any issues right now.

 Is there anything for me to do to remedy the possible merge conflict?

**Comment by larsbarring** [comment]
I do not know enough about git and github to have an idea as to why this happened. But if you rebase what happens then? Or maybe you could just remove the two rouge spaces from your PR?  --- Just a thought...

**Comment by sadielbartholomew** [comment]
> Or maybe you could just remove the two rouge spaces from your PR? --- Just a thought...

If that's essentially what needs to be done (and maybe because it is pure whitespace `git` and/or GitHub aren't raising this) then it does seem simplest to add a new commit that does that to make the problem go away. Incoming...

**Comment by sadielbartholomew** [comment]
@larsbarring (after a bit of delay from being distracted by emails) this should now be done in my new commit. Let me know if it looks right to you. And then we should finally be ready for review!

**Pull request merged**
