### PR TITLE
requirements recommendations

### PR DESCRIPTION
**Pull request by marqh**
I have added the conformance page (as html) to this repository

I think the conformance document and the conventions document are aimed to be managed in step, so this makes sense to me.

I have added the 1.6 snapshot to be consistent with the conventions content version.  
If this is adopted, we can bring in the 1.7 draft, and thus track changes

If a different format is preferred, please may content in this form be provided? The html form
was all I could find.

thank you
mark

### CODE REVIEW

**Comment by painter1** [comment]
I have to apologize for not noticing this pull request.  Last week I took the html version of the draft 1.7 conformance document and converted it to AsciiDoc (mostly; lots of variable names still have to be highlighted).  I put it in a separate repository, named cf-convention/Conformance.

I don't have any strong opinions about whether the conformance document should be in the same repository as the main CF Conventions document, or its own repository.

One thing which I am concerned about relates to a feature we have for the main document.  We have a nice system for automatically converting the master branch's AsciiDoc files into an html file, which is immediately visible to the community.  Recently this worked as it should for Ticket 145.  I would like to see the same sort of system for the conformance document, but I don't know how it works or who originally set it up.

**Comment by rsignell-usgs** [comment]
I know that everything that happens automatically upon PR or merge is controlled by 
https://github.com/cf-convention/cf-conventions/blob/master/.travis.yml
but I don't know much more than that.   

I think unfortunately @rhattersley is no longer involved with CF, but perhaps someone else from the @scitools group or @ocefpaf would be willing to help us out?

**Comment by rsignell-usgs** [comment]
Maybe it's as simple as adding a few lines here?
https://github.com/cf-convention/cf-conventions/blob/master/.travis.yml
@painter1 , what would those lines be?

**Comment by ocefpaf** [comment]
> https://github.com/cf-convention/cf-conventions/blob/master/.travis.yml#L21

I did not check the details but I do see all the parts necessary for an automatic update of the page every time a PR is merged in https://github.com/cf-convention/cf-conventions/blob/master/.travis.yml#L21

(Although nowadays I would re-write that to use `doctr` and simplify it a lot.)

**Comment by rsignell-usgs** [comment]
@painter1, ah, okay, I see you put the conformance doc in it's own repo.   So you would need to add a .travis file similar to https://github.com/cf-convention/cf-conventions/blob/master/.travis.yml and get the tokens set up there.

**Comment by dblodgett-usgs** [comment]
This PR is getting very long in the tooth. Can we agree to merge or close it for later?

**Comment by dblodgett-usgs** [comment]
Going to close and not merge. We need to figure out how to get these builds working properly.

**Pull request closed without merging**
