### PR TITLE
#72

### PR DESCRIPTION
**Pull request by reshel3**
#72 Added Geostationary projection to grid-mapping in Appendix F

### CODE REVIEW

**Comment by painter1** [comment]
The Notes section has some formatting problems.
None of the urls work any more, although they must have at the time that ticket #72 was discussed and this revision defined.  I'll try to find the currently correct ones.
Of course, the Revision History will need an entry for this.

**Comment by JonathanGregory** [comment]
Martin Raspaud should be named in the list of additional authors of the CF convention, as mentioned in comment 19 on this ticket.

**Comment by davidhassell** [comment]
I've had a little dig around on the internet, and a had a reread of http://cf-trac.llnl.gov/trac/ticket/72, and I'm fairly happy that the three broken urls:

http://www.eumetsat.int/idcplg?IdcService=GET_FILE&dDocName=PDF_CGMS_03&RevisionSelectionMethod=LatestReleased
​http://trac.osgeo.org/proj/wiki/proj%3Dgeo
​http://remotesensing.org/geotiff/proj_list/geos.html

Could now be:

www.cgms-info.org/documents/pdf_cgms_03.pdf
http://proj4.org/
https://trac.osgeo.org/geotiff/

What do you think?

**Comment by painter1** [comment]
Martin Raspaud got into the list of additional authors in another branch was was merged in earlier; I'm not sure which one.  @davidhassell's new urls are in, thanks to Tanya.  I fixed the formatting errors in the Notes section and updated the revision history, then merged with command-line tools.

**Pull request merged**
