### PR TITLE
missing ; (typo)

### PR DESCRIPTION
**Pull request by edzer**
corrected a typo

### CODE REVIEW

**Comment by erget** [comment]
These changes look good to me. @davidhassell I think [you're the lucky one to merge this in 3w](https://cfconventions.org/errors.html) if there are no objections; that would be the 13th, right in time for the workshop. Does that work for you?

**Comment by erget** [comment]
And thank you @edzer , that's clearly a typo and the correction is appreciated! :)

**Comment by davidhassell** [comment]
Hi @erget - I'm happy to merge this right now - as in 3 weeks we'll already have released CF-1.10, but I'm willing to go out on a limb and say that there is no possible objection to this defect :).

**Comment by erget** [comment]
@davidhassell I agree, I've merged it now. If the CF police comes they'll hang us together ;)

**Pull request merged**
