### PR TITLE
Remove extraneous spaces before and after punctuation

### PR DESCRIPTION
**Pull request by dnowacki-usgs**
See issue #381 for discussion of these changes.

# Release checklist
- [x] Authors updated in `cf-conventions.adoc`?
- [x] Next version in `cf-conventions.adoc` up to date? Versioning inspired by [SemVer](https://semver.org).
- [x] `history.adoc` up to date?
- [x] Conformance document up-to-date?

# For maintainers
After the merge remember to delete the source branch.
Tags are set at the conclusion of the annual meeting; until then `master` always is a draft for the next version.

### CODE REVIEW

**Comment by erget** [comment]
Sources look good. Checking build.

**Comment by erget** [comment]
[Build artefacts](https://github.com/cf-convention/cf-conventions/suites/8095409652/artifacts/361468320) look good to me as well, but I'd be happy for a second pair of eyes. It looks surgical to me, and successful. @sadielbartholomew @davidhassell or anyone else mind having a look?

**Comment by erget** [comment]
Next commit splits the paragraphs; comparison between that and the current HEAD should show no visible differences.

**Comment by sadielbartholomew** [comment]
Sure @erget, I will take a look shortly as soon as I get a chance (probably first, I think David is taking notes live to document the workshop) today.

**Comment by erget** [comment]
Superseded by https://github.com/cf-convention/cf-conventions/issues/386

**Pull request closed without merging**
